// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __object_hh__
#define __object_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_object
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_object
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_object
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



struct EntryIdl {
  typedef _CORBA_ConstrType_Variable_Var<EntryIdl> _var_type;

  
  ::CORBA::String_member first_name;

  ::CORBA::String_member last_name;

  ::CORBA::String_member father_name;

  ::CORBA::String_member phone;



  void operator>>= (cdrStream &) const;
  void operator<<= (cdrStream &);
};

typedef EntryIdl::_var_type EntryIdl_var;

typedef _CORBA_ConstrType_Variable_OUT_arg< EntryIdl,EntryIdl_var > EntryIdl_out;

typedef EntryIdl Entry_alias;
typedef EntryIdl_var Entry_alias_var;
typedef EntryIdl_out Entry_alias_out;

#ifndef __MyInterface__
#define __MyInterface__
class MyInterface;
class _objref_MyInterface;
class _impl_MyInterface;

typedef _objref_MyInterface* MyInterface_ptr;
typedef MyInterface_ptr MyInterfaceRef;

class MyInterface_Helper {
public:
  typedef MyInterface_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_MyInterface, MyInterface_Helper> MyInterface_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_MyInterface,MyInterface_Helper > MyInterface_out;

#endif

// interface MyInterface
class MyInterface {
public:
  // Declarations for this interface type.
  typedef MyInterface_ptr _ptr_type;
  typedef MyInterface_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  class Entries_var;

  class Entries : public _CORBA_Unbounded_Sequence< EntryIdl >  {
  public:
    typedef Entries_var _var_type;
    inline Entries() {}
    inline Entries(const Entries& _s)
      : _CORBA_Unbounded_Sequence< EntryIdl > (_s) {}

    inline Entries(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence< EntryIdl > (_max) {}
    inline Entries(_CORBA_ULong _max, _CORBA_ULong _len, EntryIdl* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence< EntryIdl > (_max, _len, _val, _rel) {}

  

    inline Entries& operator = (const Entries& _s) {
      _CORBA_Unbounded_Sequence< EntryIdl > ::operator=(_s);
      return *this;
    }
  };

  class Entries_out;

  class Entries_var {
  public:
    inline Entries_var() : _pd_seq(0) {}
    inline Entries_var(Entries* _s) : _pd_seq(_s) {}
    inline Entries_var(const Entries_var& _s) {
      if (_s._pd_seq)  _pd_seq = new Entries(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~Entries_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline Entries_var& operator = (Entries* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline Entries_var& operator = (const Entries_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new Entries;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline EntryIdl& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline Entries* operator -> () { return _pd_seq; }
    inline const Entries* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator Entries& () const { return *_pd_seq; }
#else
    inline operator const Entries& () const { return *_pd_seq; }
    inline operator Entries& () { return *_pd_seq; }
#endif
      
    inline const Entries& in() const { return *_pd_seq; }
    inline Entries&       inout()    { return *_pd_seq; }
    inline Entries*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline Entries* _retn() { Entries* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class Entries_out;
    
  private:
    Entries* _pd_seq;
  };

  class Entries_out {
  public:
    inline Entries_out(Entries*& _s) : _data(_s) { _data = 0; }
    inline Entries_out(Entries_var& _s)
      : _data(_s._pd_seq) { _s = (Entries*) 0; }
    inline Entries_out(const Entries_out& _s) : _data(_s._data) {}
    inline Entries_out& operator = (const Entries_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline Entries_out& operator = (Entries* _s) {
      _data = _s;
      return *this;
    }
    inline operator Entries*&()  { return _data; }
    inline Entries*& ptr()       { return _data; }
    inline Entries* operator->() { return _data; }

    inline EntryIdl& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    Entries*& _data;

  private:
    Entries_out();
    Entries_out& operator=(const Entries_var&);
  };


};

class _objref_MyInterface :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  MyInterface::Entries* load();

  // Constructors
  inline _objref_MyInterface()  { _PR_setobj(0); }  // nil
  _objref_MyInterface(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_MyInterface();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_MyInterface(const _objref_MyInterface&);
  _objref_MyInterface& operator = (const _objref_MyInterface&);
  // not implemented

  friend class MyInterface;
};

class _pof_MyInterface : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_MyInterface() : _OMNI_NS(proxyObjectFactory)(MyInterface::_PD_repoId) {}
  virtual ~_pof_MyInterface();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_MyInterface :
  public virtual omniServant
{
public:
  virtual ~_impl_MyInterface();

  virtual MyInterface::Entries* load() = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_MyInterface :
  public virtual _impl_MyInterface,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_MyInterface();

  inline ::MyInterface_ptr _this() {
    return (::MyInterface_ptr) _do_this(::MyInterface::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
MyInterface::_marshalObjRef(::MyInterface_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_object
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_object
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_object
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_object
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_object
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_object
#endif

#endif  // __object_hh__

